--------------------------------------------------------
--  File created - Friday-January-17-2020
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRIREZI
--------------------------------------------------------

  CREATE TABLE "PRIREZI"
   (	"ID" NUMBER(6),
	"MJESTO" VARCHAR2(26),
	"IZNOS" NUMBER(4,2)
   )
Insert into PRIREZI (ID,MJESTO,IZNOS) values (1,'Andrijaševci',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (2,'Antunovac',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (3,'Babina Greda',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (4,'Bale',1);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (5,'Barban',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (6,'Bedenica',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (7,'Bednja',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (8,'Beli Manastir',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (9,'Belica',1);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (10,'Belišće',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (11,'Benkovac',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (12,'Beretinec',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (13,'Bilice',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (14,'Bilje',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (15,'Biograd na Moru',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (16,'Biskupija',4);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (17,'Bistra',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (18,'Bizovac',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (19,'Bjelovar',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (20,'Blato',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (21,'Bol',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (22,'Borovo',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (23,'Bošnjaci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (24,'Brckovljani',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (25,'Brdovec',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (26,'Brela',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (27,'Brestovac',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (28,'Breznica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (29,'Breznički Hum',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (30,'Brinje',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (31,'Brodski Stupnik',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (32,'Buje',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (33,'Bukovlje',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (34,'Buzet',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (35,'Cerna',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (36,'Cernik',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (37,'Cerovlje',2);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (38,'Cestica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (39,'Cista Provo',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (40,'Civljane',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (41,'Crikvenica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (42,'Čabar',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (43,'Čaglin',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (44,'Čakovec',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (45,'Čazma',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (46,'Čeminac',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (47,'Čepin',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (48,'Darda',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (49,'Daruvar',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (50,'Davor',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (51,'Delnice',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (52,'Dežanovac',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (53,'Dicmo',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (54,'Donja Stubica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (55,'Donja Voća',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (56,'Donji Andrijevci',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (57,'Donji Kukuruzari',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (58,'Donji Lapac',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (59,'Donji Martijanec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (60,'Donji Miholjac',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (61,'Dragalić',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (62,'Draž',2);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (63,'Drenovci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (64,'Drniš',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (65,'Dubrava',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (66,'Dubravica',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (67,'Dubrovačko primorje',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (68,'Dubrovnik',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (69,'Duga Resa',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (70,'Dugo Selo',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (71,'Dugopolje',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (72,'Dvor',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (73,'Đakovo',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (74,'Đurđenovac',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (75,'Erdut',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (76,'Ernestinovo',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (77,'Ervenik',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (78,'Farkaševac',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (79,'Fažana',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (80,'Feričanci',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (81,'Fužine',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (82,'Garčin',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (83,'Garešnica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (84,'Gornji Bogićevci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (85,'Gornji Kneginec',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (86,'Gospić',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (87,'Gračac',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (88,'Gračišće',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (89,'Gradec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (90,'Grubišno Polje',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (91,'Gunja',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (92,'Hrašćina',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (93,'Hrvace',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (94,'Hrvatska Dubica',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (95,'Hrvatska Kostajnica',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (96,'Ilok',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (97,'Imotski',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (98,'Ivanec',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (99,'Ivanić grad',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (100,'Ivankovo',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (101,'Jagodnjak',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (102,'Jakovlje',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (103,'Jakšić',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (104,'Jastrebarsko',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (105,'Jelsa',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (106,'Kamanje',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (107,'Kanfanar',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (108,'Kapela',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (109,'Kaptol',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (110,'Karlovac',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (111,'Karojba',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (112,'Kaštela',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (113,'Kaštelir-Labinci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (114,'Kijevo',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (115,'Kistanje',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (116,'Klanjec',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (117,'Klenovnik',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (118,'Klinča Sela',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (119,'Klis',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (120,'Kloštar Ivanić',2);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (121,'Kloštar Podravski',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (122,'Kneževi Vinogradi',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (123,'Knin',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (124,'Komiža',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (125,'Konavle',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (126,'Končanica',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (127,'Konjšćina',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (128,'Korčula',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (129,'Kraljevica',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (130,'Krašić',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (131,'Kravarsko',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (132,'Križ',2);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (133,'Križevci',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (134,'Krnjak',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (135,'Kula Norinska',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (136,'Kutina',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (137,'Labin',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (138,'Lanišće',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (139,'Lasinja',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (140,'Lastovo',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (141,'Lepoglava',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (142,'Lipik',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (143,'Lipovljani',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (144,'Lišane Ostrovičke',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (145,'Ližnjan',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (146,'Lokvičići',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (147,'Lovas',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (148,'Lovinac',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (149,'Ludbreg',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (150,'Luka',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (151,'Lukač',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (152,'Lumbarda',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (153,'Lupoglav',1);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (154,'Ljubešćica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (155,'Magadenovac',2);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (156,'Majur',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (157,'Makarska',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (158,'Mali Bukovec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (159,'Marčana',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (160,'Marija Gorica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (161,'Marijanci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (162,'Markušica',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (163,'Maruševec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (164,'Matulji',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (165,'Medulin',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (166,'Metković',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (167,'Milna',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (168,'Mljet',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (169,'Motovun',1);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (170,'Mrkopalj',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (171,'Muć',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (172,'Murter-Kornati',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (173,'Našice',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (174,'Negoslavci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (175,'Nova Gradiška',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (176,'Nova Kapela',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (177,'Novi Marof',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (178,'Novi Vinodolski',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (179,'Novska',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (180,'Nuštar',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (181,'Ogulin',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (182,'Okučani',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (183,'Omiš',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (184,'Opatija',7.5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (185,'Opuzen',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (186,'Orle',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (187,'Osijek',13);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (188,'Otočac',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (189,'Otok (Sinj)',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (190,'Otok (Vinkovci)',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (191,'Ozalj',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (192,'Pakrac',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (193,'Pazin',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (194,'Perušić',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (195,'Petlovac',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (196,'Petrijanec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (197,'Petrijevci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (198,'Petrinja',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (199,'Pićan',2);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (200,'Pirovac',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (201,'Pisarovina',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (202,'Pleternica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (203,'Plitvička jezera',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (204,'Ploče',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (205,'Podbablje',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (206,'Podcrkavlje',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (207,'Podgora',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (208,'Podgorač',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (209,'Podstrana',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (210,'Pokupsko',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (211,'Polača',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (212,'Popovac',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (213,'Popovača',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (214,'Požega',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (215,'Pregrada',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (216,'Preseka',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (217,'Primošten',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (218,'Proložac',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (219,'Promina',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (220,'Pučišća',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (221,'Pula',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (222,'Pušća',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (223,'Rakovec',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (224,'Rakovica',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (225,'Raša',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (226,'Ravna Gora',7.5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (227,'Rešetari',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (228,'Ribnik',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (229,'Rijeka',15);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (230,'Rovinj',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (231,'Rugvica',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (232,'Runovići',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (233,'Ružić',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (234,'Senj',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (235,'Sibinj',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (236,'Sinj',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (237,'Sisak',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (238,'Skradin',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (239,'Slatina',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (240,'Slavonski Brod',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (241,'Slunj',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (242,'Solin',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (243,'Split',15);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (244,'Sračinec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (245,'Stara Gradiška',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (246,'Stari Grad',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (247,'Stari Mikanovci',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (248,'Staro Petrovo Selo',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (249,'Stupnik',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (250,'Supetar',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (251,'Sutivan',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (252,'Sveta Nedelja (Labin)',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (253,'Sveta Nedjelja (Samobor)',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (254,'Sveti Đurđ',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (255,'Sveti Filip i Jakov',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (256,'Sveti Ilija',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (257,'Sveti Ivan Zelina',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (258,'Sveti Lovreč',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (259,'Sveti Petar u Šumi',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (260,'Svetvinčenat',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (261,'Šibenik',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (262,'Škabrnja',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (263,'Špišić Bukovica',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (264,'Štefanje',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (265,'Štitar',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (266,'Tinjan',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (267,'Tisno',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (268,'Tordinci',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (269,'Tribunj',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (270,'Trnovec Bartolovečki',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (271,'Trogir',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (272,'Trpanj',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (273,'Tučepi',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (274,'Udbina',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (275,'Umag',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (276,'Unešić',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (277,'Valpovo',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (278,'Varaždin',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (279,'Varaždinske Toplice',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (280,'Vela Luka',9);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (281,'Velika Gorica',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (282,'Velika Kopanica',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (283,'Veliki Bukovec',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (284,'Veliko Trgovišće',7.5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (285,'Vidovec',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (286,'Vinica',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (287,'Vinkovci',13);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (288,'Virovitica',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (289,'Vis',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (290,'Visoko',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (291,'Višnjan',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (292,'Vižinada',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (293,'Vladislavci',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (294,'Vodice',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (295,'Vodnjan',7.5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (296,'Vođinci',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (297,'Vojnić',7.5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (298,'Vrbanja',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (299,'Vrbje',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (300,'Vrbovec',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (301,'Vrbovsko',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (302,'Vrgorac',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (303,'Vrhovine',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (304,'Vrlika',7);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (305,'Zadar',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (306,'Zadvarje',1);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (307,'Zagreb',18);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (308,'Zagvozd',6);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (309,'Zaprešić',12);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (310,'Zlatar',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (311,'Zlatar Bistrica',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (312,'Zmijavci',8);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (313,'Žakanje',0);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (314,'Žminj',5);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (315,'Žumberak',3);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (316,'Župa Dubrovačka',10);
Insert into PRIREZI (ID,MJESTO,IZNOS) values (317,'Županja',12);
--------------------------------------------------------
--  Constraints for Table PRIREZI
--------------------------------------------------------

  ALTER TABLE "PRIREZI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRIREZI" MODIFY ("MJESTO" NOT NULL ENABLE);
  ALTER TABLE "PRIREZI" MODIFY ("IZNOS" NOT NULL ENABLE);
